image: golang:1.12

variables:
  DOCKER_HOST: tcp://localhost:2375
  PROJECT_URL: gitlab.nbaplus.tk/backend/queue
  PROJECT_NAME: queue
  GOPROXY: https://goproxy.nbaplus.tk

stages:
  - lint
  - test

lint:
  stage: lint
  image: golangci/golangci-lint:v1.17.1
  script:
    - go mod download
    - golangci-lint run

test:
  stage: test
  script:
    - go mod download
    - go vet $(go list ./...)
    - go test -cover -race $(go list ./...)